-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 19:27:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banco_tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_tcc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `banco_tcc` ;

-- -----------------------------------------------------
-- Table `banco_tcc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `bio` VARCHAR(500) NULL DEFAULT NULL,
  `foto_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `total_perguntas` INT UNSIGNED NULL DEFAULT '0',
  `total_respostas` INT UNSIGNED NULL DEFAULT '0',
  `total_conquistas` INT UNSIGNED NULL DEFAULT '0',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_email` (`email` ASC) VISIBLE,
  INDEX `idx_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_criado_em` (`criado_em` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`conquistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`conquistas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `icone` VARCHAR(50) NULL DEFAULT NULL,
  `tipo` ENUM('perguntas', 'respostas', 'quizzes', 'especial') NULL DEFAULT 'especial',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_tipo` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_conquistas_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`log_perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`log_perguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pergunta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `acao` ENUM('criacao', 'edicao', 'remocao', 'arquivamento') NOT NULL,
  `dados_anteriores` JSON NULL DEFAULT NULL,
  `dados_novos` JSON NULL DEFAULT NULL,
  `data_log` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_pergunta_id` (`pergunta_id` ASC) VISIBLE,
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_acao` (`acao` ASC) VISIBLE,
  INDEX `idx_data_log` (`data_log` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`log_respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`log_respostas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resposta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `acao` ENUM('criacao', 'edicao', 'remocao') NOT NULL,
  `dados_anteriores` JSON NULL DEFAULT NULL,
  `dados_novos` JSON NULL DEFAULT NULL,
  `data_log` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_resposta_id` (`resposta_id` ASC) VISIBLE,
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_acao` (`acao` ASC) VISIBLE,
  INDEX `idx_data_log` (`data_log` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`metas_semanal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`metas_semanal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `meta_perguntas` TINYINT UNSIGNED NULL DEFAULT '5',
  `meta_respostas` TINYINT UNSIGNED NULL DEFAULT '5',
  `meta_quizzes` TINYINT UNSIGNED NULL DEFAULT '3',
  `perguntas_realizadas` TINYINT UNSIGNED NULL DEFAULT '0',
  `respostas_realizadas` TINYINT UNSIGNED NULL DEFAULT '0',
  `quizzes_realizados` TINYINT UNSIGNED NULL DEFAULT '0',
  `semana_inicio` DATE NOT NULL,
  `semana_fim` DATE NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_usuario_semana` (`usuario_id` ASC, `semana_inicio` ASC) VISIBLE,
  INDEX `idx_semana_inicio` (`semana_inicio` ASC) VISIBLE,
  CONSTRAINT `fk_metas_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`pergunta_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`pergunta_quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enunciado` TEXT NOT NULL,
  `categoria` VARCHAR(100) NULL DEFAULT NULL,
  `dificuldade` ENUM('facil', 'medio', 'dificil') NULL DEFAULT 'medio',
  `opcoes` JSON NOT NULL,
  `resposta_index` TINYINT UNSIGNED NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_categoria` (`categoria` ASC) VISIBLE,
  INDEX `idx_dificuldade` (`dificuldade` ASC) VISIBLE,
  INDEX `idx_ativo` (`ativo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`perguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `dificuldade` ENUM('facil', 'medio', 'dificil') NULL DEFAULT 'medio',
  `visualizacoes` INT UNSIGNED NULL DEFAULT '0',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_categoria` (`categoria` ASC) VISIBLE,
  INDEX `idx_dificuldade` (`dificuldade` ASC) VISIBLE,
  INDEX `idx_criado_em` (`criado_em` ASC) VISIBLE,
  FULLTEXT INDEX `idx_busca` (`titulo`, `conteudo`) VISIBLE,
  CONSTRAINT `fk_perguntas_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`perguntas_arquivadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`perguntas_arquivadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pergunta_id` INT NOT NULL COMMENT 'ID original da pergunta',
  `usuario_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `dificuldade` ENUM('facil', 'medio', 'dificil') NULL DEFAULT 'medio',
  `arquivado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `criado_em` TIMESTAMP NOT NULL,
  `atualizado_em` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_pergunta_id` (`pergunta_id` ASC) VISIBLE,
  INDEX `idx_arquivado_em` (`arquivado_em` ASC) VISIBLE,
  CONSTRAINT `fk_perguntas_arq_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`quiz_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`quiz_resultados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `dificuldade` ENUM('facil', 'medio', 'dificil') NULL DEFAULT NULL,
  `acertos` TINYINT UNSIGNED NOT NULL,
  `total` TINYINT UNSIGNED NOT NULL,
  `tempo_gasto` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Tempo em segundos',
  `pontuacao` DECIMAL(5,2) NULL DEFAULT NULL COMMENT 'Percentual de acerto',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_categoria` (`categoria` ASC) VISIBLE,
  INDEX `idx_dificuldade` (`dificuldade` ASC) VISIBLE,
  INDEX `idx_criado_em` (`criado_em` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_resultados_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_tcc`.`respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_tcc`.`respostas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `pergunta_id` INT NOT NULL,
  `conteudo` TEXT NOT NULL,
  `melhor_resposta` TINYINT(1) NULL DEFAULT '0',
  `curtidas` INT UNSIGNED NULL DEFAULT '0',
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_pergunta_id` (`pergunta_id` ASC) VISIBLE,
  INDEX `idx_melhor_resposta` (`melhor_resposta` ASC) VISIBLE,
  INDEX `idx_criado_em` (`criado_em` ASC) VISIBLE,
  CONSTRAINT `fk_respostas_pergunta`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `banco_tcc`.`perguntas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respostas_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco_tcc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `banco_tcc`;

DELIMITER $$
USE `banco_tcc`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `banco_tcc`.`trg_after_insert_pergunta`
AFTER INSERT ON `banco_tcc`.`perguntas`
FOR EACH ROW
BEGIN
    UPDATE usuarios 
    SET total_perguntas = total_perguntas + 1 
    WHERE id = NEW.usuario_id;
END$$

USE `banco_tcc`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `banco_tcc`.`trg_before_insert_quiz_resultado`
BEFORE INSERT ON `banco_tcc`.`quiz_resultados`
FOR EACH ROW
BEGIN
    SET NEW.pontuacao = (NEW.acertos / NEW.total) * 100;
END$$

USE `banco_tcc`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `banco_tcc`.`trg_after_insert_resposta`
AFTER INSERT ON `banco_tcc`.`respostas`
FOR EACH ROW
BEGIN
    UPDATE usuarios 
    SET total_respostas = total_respostas + 1 
    WHERE id = NEW.usuario_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
